### ISSUE TITLE
代码里面的域名被污染了

### ISSUE THREAD

**Issue by bynowi** [rememberber/MooTool#105]
zhoubochina.com 这个域名被污染了
![1706087777447](https://github.com/rememberber/MooTool/assets/20673319/5dcd8bf5-bd80-43a2-a5d3-41d43da621bd)
![微信截图_20240124171716](https://github.com/rememberber/MooTool/assets/20673319/da8e1a6a-78b2-4077-ae11-ab6d0c38054b)

**Comment by rememberber** [comment]
属于无用代码
