### ISSUE TITLE
切换“外观/主题风格”时会生成一条JSON和Host记录

### ISSUE THREAD

**Issue by bynowi** [rememberber/MooTool#106]
在切换主题样式时，会生成一条JSON和一条Host记录，复现时请先清空JSON和Host里面的记录。哪一个里面没有记录就会生成一条记录，当JSON和Host里有记录时不会生成。
![1706145780069](https://github.com/rememberber/MooTool/assets/20673319/223d144a-e91c-48bf-a0cd-999106406d02)

**Comment by rememberber** [comment]
已修复
