### ISSUE TITLE
Mac下窗口会自动铺满屏幕bug

### ISSUE THREAD

**Issue by lhpqaq** [rememberber/MooTool#110]
缩小化窗口，再次使MooTool主窗口出现在最前面后，会自动铺满屏幕。
比如点击取消后，回到MooTool主窗口会自动放大到铺满屏幕

<img width="1470" alt="截屏2024-08-28 17 42 21" src="https://github.com/user-attachments/assets/ee54d3f3-e18b-4444-9651-e289da767de5">

此外最小化窗口，再次点击MooTool也会自动铺满屏幕

Mac OS 14.4.1

**Comment by rememberber** [comment]
@lhpqaq 菜单->外观->默认窗口最大化，取消掉这个勾选
