### ISSUE TITLE
Execute main class of App.java failed

### ISSUE THREAD

**Issue by ansonliao** [rememberber/MooTool#49]
Hi @rememberber ,
Thanks for your great work on providing this awesome tool and present the powerful of Java Swing framework on creating the GUI application.

I clone the repo and try to execute the application on my machine, but meet some problems, my machine configuration as below:
- Machine: macOS 12.2, Apple M1 pro chip
- Memory: 32 GB
- Java version: 1.8.0_292
- Maven version: 3.8.4 or IntelliJ Ultimate built Maven 3
- IDE: IntelliJ Ultimate 2021.3.2

When I execute main method of App.java, meet the error as below:
```shell
/repos/github/MooTool/src/main/java/com/luoboduner/moo/tool/ui/listener/func/QuickNoteListener.java:10:40
java: cannot access com.google.googlejavaformat.java.Formatter
  bad class file: /apps/maven/.m2/repository/com/google/googlejavaformat/google-java-format/1.13.0/google-java-format-1.13.0.jar!/com/google/googlejavaformat/java/Formatter.class
    class file has wrong version 55.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
```

Could you kindly help to advise how can I fix the issue?

Thanks.

**Comment by rememberber** [comment]
You need to upgrade Java version to 17

**Comment by ansonliao** [comment]
Switched to Java 17 and re-execute App.java, it can launch the GUI now.

But checked pom.xml file, found it specified Java version to 1.8, as below
https://github.com/rememberber/MooTool/blob/master/pom.xml#L21

![image](https://user-images.githubusercontent.com/6060224/153167492-a5fe039d-ba4d-4f8b-b97d-b4b8fc66a295.png)

is there any confuse on it?

**Comment by rememberber** [comment]
@ansonliao Oh, the pom file is wrong, thanks for fingering that, I will fix it

**Comment by ansonliao** [comment]
Hi @rememberber, Thanks for your reply
