### ISSUE TITLE
优化体验

### ISSUE THREAD

**Issue by orange-juzipi** [rememberber/MooTool#79]
在`调色板`中，右上角的`复制`按钮，点击复制后，建议去掉`已复制`的弹窗，太影响体验了，可以不显示或者把`复制`替换为`已复制`。
在其他的卡片面板中，也可以尝试把不必要的弹窗，替换为`消息`提醒类型，减少用户的鼠标点击次数，体验会更加好。

**Comment by rememberber** [comment]
@orange-juzipi 已优化，更新试试
