### ISSUE TITLE
正规表达式显示问题

### ISSUE THREAD

**Issue by smallclover** [rememberber/MooTool#82]
# 正则表示表示问题

## 问题：当正则表达式超过一定长度，组件会发生偏移
![image](https://github.com/rememberber/MooTool/assets/10950966/53d16ab4-7b47-43e2-bfe3-1368ea069236)

## 解决思路：超过一定位数表示为【...】
![image](https://github.com/rememberber/MooTool/assets/10950966/16367794-2d18-4730-a229-0e6d5be253d2)

**Comment by rememberber** [comment]
@smallclover 多谢，我解决下
