### ISSUE TITLE
正则表达式入力框是否需要滚动条

### ISSUE THREAD

**Issue by smallclover** [rememberber/MooTool#83]
# 功能：正则表达式
> 当入力的文本超过一定长度的时候是否需要滚动条

下面这个图是我追加上去的效果，不过一般的使用场景好像不会超过这个长度，不知道需不需要。

![image](https://github.com/rememberber/MooTool/assets/10950966/a4e650cc-b201-4b05-a309-23bbe8c53a28)

**Comment by rememberber** [comment]
我有点好奇是什么场景表达式会这么长
