### ISSUE TITLE
mac上面闪退

### ISSUE THREAD

**Issue by yzytmac** [rememberber/MooTool#9]
mac系统是10.14.6 (18G95),Mootool版本是1.1.0,打开就自动关闭了

**Comment by 0x0021** [comment]
10.15 (19A602)  
openjdk version "12.0.2" 2019-07-16
OpenJDK Runtime Environment (build 12.0.2+10)
OpenJDK 64-Bit Server VM (build 12.0.2+10, mixed mode, sharing)

同样闪退

**Comment by rememberber** [comment]
各位好，麻烦试一下http://download.zhoubochina.com/moo/mac/MooToolWithJre-v1.2.0.zip
看看这个能不能正常运行
