### ISSUE TITLE
系统托盘菜单对主界面刷新的影响

### ISSUE THREAD

**Issue by smallclover** [rememberber/MooTool#91]
> 问题描述：当我点击系统托盘的菜单栏的时候，发现会对主界面产生影响，时间转换界面的时间会停止刷新，软件更新的进度条会停止，当菜单栏消失的时候有回到正常

> 问题原因：参照https://stackoverflow.com/questions/38200403/how-to-prevent-the-trayicon-popup-to-occupy-the-whole-dispatcher-thread
> 似乎是PopupMenu控件的问题

> 解决思路：https://lanlan2017.github.io/blog/2b294c47/
> 改成JDialog+JPopupMenu，通过监听Mouse事件的方式实现系统托盘菜单栏

## 时间转换
![image](https://github.com/rememberber/MooTool/assets/10950966/f700a1d3-0229-42d3-a131-e8b4726f2687)

## 软件更新
![image](https://github.com/rememberber/MooTool/assets/10950966/5f03bf02-8e02-4c65-93df-ea0e490e2410)

##  效果
> 1.避免了主界面刷新的问题
![image](https://github.com/rememberber/MooTool/assets/10950966/36ba7ac8-9d63-41ae-ac5d-27eb75a21b79)

ps：托盘菜单栏的位置我SetLocation的x坐标总是差300左右，不知为何

**Comment by rememberber** [comment]
已按你的提示更新
